[package]
name = "vicocomo_example_postgres"
version = "0.1.6"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
chrono = "*"
dotenv = "*"
futures = "*"
tokio = { version = "*", features = ["macros", "rt-threaded"] }
tokio-postgres = "*"
vicocomo = { path = "../../.." }
vicocomo_postgres = { path = "../../../vicocomo_postgres" }

