[package]
name = "vicocomo_example_postgres"
version = "0.1.22"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
dotenv = "0.15"
futures = "0.3.13"
tokio = { version = "0.2.25", features = ["macros", "rt-threaded"] }
tokio-postgres = "0.5.5"
vicocomo = { path = "../../.." }
vicocomo_postgres = { path = "../../../vicocomo_postgres" }

