[package]
name = "vicocomo_example_postgres"
version = "0.1.15"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
chrono = "*"
dotenv = "*"
futures = "*"
tokio = { version = "0.2.22", features = ["full"] }
tokio-postgres = "0.5.5"
vicocomo = { path = "../../.." }
vicocomo_postgres = { path = "../../../vicocomo_postgres" }

