[package]
name = "vicocomo_postgres"
version = "0.2.0"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
futures = "0.3.21"
tokio-postgres = "0.7.6"
postgres-types = "0.2.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
vicocomo = { path = ".." }

