[package]
name = "vicocomo_postgres"
version = "0.1.13"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
futures = "*"
tokio-postgres = "*"
postgres-types = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
vicocomo = { path = ".." }

