[package]
name = "vicocomo_postgres"
version = "0.1.22"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
futures = "*"
tokio-postgres = "0.5.5"
postgres-types = "0.1.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
vicocomo = { path = ".." }

