[package]
name = "vicocomo"
version = "0.4.0"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2021"

[dependencies]
case = "1.0.0"
chrono = { version = "0.4.22", features = ["serde"] }
itertools = "0.10.4"
lazy_static = "1.4.0"
proc-macro2 = "1.0.43"
quote = "1.0.21"
rand = "0.8.5"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
syn = { version = "1.0.99", features = ["full", "extra-traits"] }
v_htmlescape = "0.15.8"
urlencoding = "2.1.2"
vicocomo_active_record = { path = "vicocomo_active_record" }
vicocomo_db_macros = { path = "vicocomo_db_macros" }
vicocomo_derive_utils = { path = "vicocomo_derive_utils" }
vicocomo_html_macros = { path = "vicocomo_html_macros" }
vicocomo_session_model = { path = "vicocomo_session_model" }
