[package]
name = "vicocomo"
version = "0.1.3"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
diesel = "*"
itertools = "*"
serde = { version = "*", features = ["derive"] }
vicocomo_derive = { path = "vicocomo_derive" }
