[package]
name = "vicocomo"
version = "0.2.0-1"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
case = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
itertools = "0.10.3"
lazy_static = "1.4"
proc-macro2 = "1.0.39"
quote = "1.0.18"
rand = "0.8.5"
regex = "1.5.6"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
syn = { version = "1.0.95", features = ["full", "extra-traits"] }
v_htmlescape = "0.14.1"
vicocomo_active_record = { path = "vicocomo_active_record" }
vicocomo_db_macros = { path = "vicocomo_db_macros" }
vicocomo_derive_utils = { path = "vicocomo_derive_utils" }
vicocomo_html_macros = { path = "vicocomo_html_macros" }
vicocomo_session_model = { path = "vicocomo_session_model" }
