[package]
name = "vicocomo"
version = "0.1.5"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
chrono = "*"
itertools = "*"
serde = { version = "*", features = ["derive"] }
vicocomo_db_macro = { path = "vicocomo_db_macro" }
vicocomo_derive_utils = { path = "vicocomo_derive_utils" }
vicocomo_html_derive = { path = "vicocomo_html_derive" }
vicocomo_model_derive = { path = "vicocomo_model_derive" }
vicocomo_route_macro = { path = "vicocomo_route_macro" }
