[package]
name = "vicocomo"
version = "0.1.5"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
itertools = "*"
serde = { version = "*", features = ["derive"] }
vicocomo_proc_macro = { path = "vicocomo_proc_macro" }
