actix-files = "0.5"
actix-rt = "1.1.1"
actix-session = "0.4"
actix-web = "3.3.2"
case = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15"
futures = "0.3.13"
handlebars = { version = "3.5.3", features = ["dir_source"] }
itertools = "0.10"
lazy_static = "1.4"
postgres-types = "0.1.3"
proc-macro2 = "1.0.24"
quote = "1.0.9"
rand = "0.8.3"
regex = "1.4.4"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
syn = { version = "1.0.63", features = ["full", "extra-traits"] }
tokio = { version = "0.2.25", features = ["macros", "rt-threaded"] }
tokio-postgres = "0.5.5"
urlencoding = "1.1.1"
v_htmlescape = "0.12"

