[package]
name = "vicocomo_handlebars"
version = "0.1.8"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
futures = "*"
handlebars = "2.0"
serde = { version = "*", features = ["derive"] }
vicocomo = { path = ".." }

