[package]
name = "vicocomo_handlebars"
version = "0.1.22"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
futures = "0.3.13"
handlebars = { version = "3.5.3", features = ["dir_source"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
vicocomo = { path = ".." }

