[package]
name = "vicocomo_handlebars"
version = "0.1.14"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
futures = "*"
handlebars = { version = "*", features = ["dir_source"] }
serde = { version = "*", features = ["derive"] }
vicocomo = { path = ".." }

