[package]
name = "vicocomo_example_http_server_if"
version = "0.3.0"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
chrono = "*"
serde_json = "*"
vicocomo = { path = "../../.." }
vicocomo_stubs = { path = "../../../vicocomo_stubs" }
