[package]
name = "vicocomo_derive_utils"
version = "0.1.22"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
case = "1.0"
proc-macro2 = "1.0.24"
quote = "1.0.9"
regex = "1.4.4"
syn = { version = "1.0.63", features = ["full", "extra-traits"] }

