[package]
name = "vicocomo_derive_utils"
version = "0.1.16"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
case = "*"
proc-macro2 = "*"
quote = "*"
regex = "*"
syn = { version = "*", features = ["full", "extra-traits", "clone-impls"] }

