[package]
name = "vicocomo_derive_utils"
version = "0.3.0"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
case = "1"
proc-macro2 = "1.0.39"
quote = "1.0.18"
regex = "1.5.6"
syn = { version = "1.0.95", features = ["full", "extra-traits"] }

