[package]
name = "vicocomo_bcrypt"
version = "0.4.2"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2021"

[dependencies]
bcrypt = "0.14.0"
lazy_static = "1.4.0"
vicocomo = { path = ".." }

