[package]
name = "vicocomo_bcrypt"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bcrypt.workspace = true
vicocomo = { path = "../vicocomo", version = "1.0.0" }

