[workspace]

[package]
name = "vicocomo_example_model_common"
version = "0.5.0"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2021"

[dependencies]
chrono = "0.4.23"
lazy_static = "1.4.0"
vicocomo = { path = "../../.." }

