[package]
name = "vicocomo_actix"
version = "0.4.0"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-rt = "2.7.0"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
actix-web = "4.2.1"
chrono = "0.4.22"
lazy_static = "1.4.0"
regex = "1.6.0"
serde_json = "1.0.85"
vicocomo = { path = ".." }
vicocomo_actix_config = { path = "config" }
