[package]
name = "vicocomo_actix"
version = "0.1.22"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
actix-files = "0.5"
actix-rt = "1.1.1"
actix-session = "0.4"
actix-web = "3.3.2"
chrono = "0.4.19"
lazy_static = "1.4"
rand = "0.8.3"
regex = "1.4.4"
serde_json = "1.0.64"
urlencoding = "1.1.1"
vicocomo = { path = ".." }
vicocomo_actix_config = { path = "config" }
