[package]
name = "vicocomo_actix"
version = "0.1.10"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
actix-files = "*"
actix-rt = "*"
actix-session = "*"
actix-web = "*"
lazy_static = "*"
regex = "*"
urlencoding = "*"
vicocomo = { path = ".." }
vicocomo_actix_config = { path = "config" }
