[package]
name = "vicocomo_actix"
version = "0.3.0"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
actix-files = "0.6"
actix-rt = "2.7"
actix-session = { version = "0.6.2", features = ["cookie-session"] }
actix-web = "4.0.1"
chrono = "0.4.19"
lazy_static = "1.4"
regex = "1.5.6"
serde_json = "1.0.81"
urlencoding = "1.3.3"
vicocomo = { path = ".." }
vicocomo_actix_config = { path = "config" }
