[workspace]

[package]
name = "vicocomo_example_model_postgres"
version = "0.6.0"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2021"

[dependencies]
dotenv = "0.15.0"
futures = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
tokio-postgres = "0.7.7"
vicocomo = { path = "../../.." }
vicocomo_example_model_common = { path = "../common" }
vicocomo_postgres = { path = "../../../../vicocomo_postgres" }

