[workspace]

[package]
name = "vicocomo_example_http_server_local"
version = "0.6.0"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
vicocomo = { path = "../../.." }
vicocomo_handlebars = { path = "../../../../vicocomo_handlebars" }
vicocomo_sqlite = { path = "../../../../vicocomo_sqlite" }
