[package]
name = "vicocomo_example_actix"
version = "0.1.16"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
actix-files = "*"
actix-rt = "*"
actix-session = "*"
actix-web = "*"
dotenv = "*"
lazy_static = "*"
regex = "*"
serde = { version = "*", features = ["derive"] }
tokio = { version = "0.2.22", features = ["full"] }
tokio-postgres = "0.5.5"
vicocomo = { path = "../../.." }
vicocomo_actix = { path = "../../../vicocomo_actix" }
vicocomo_handlebars = { path = "../../../vicocomo_handlebars" }

