[package]
name = "vicocomo_stubs"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
vicocomo = { path = "../vicocomo", version = "0.5.0" }
