[package]
name = "vicocomo_stubs"
version = "0.1.22"
authors = ["Anders Lindeberg <ajl@andersjlindeberg.se>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
vicocomo = { path = ".." }

